apiVersion: v1
kind: Service
metadata:
  name: expenses-ui-service
  namespace: default
  labels:
    app: expenses-ui
spec:
  selector:
    app: expenses-ui-pod
  ports:
    - name: http
      port: 80
      targetPort: 80
