apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: default
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-pod
  template:
    metadata:
      labels:
        app: auth-service-pod
    spec:
      containers:
        - image: ghcr.io/crisszkutnik/auth-service:1.0.1
          imagePullPolicy: IfNotPresent
          name: auth-service-container
          resources:
            limits:
              memory: "512Mi"
              cpu: 1
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: DB_URL
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: PORT
            - name: CF_POLICY_AUD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: CF_POLICY_AUD
