apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth-service
  - dollar-data-to-google-sheets-etl
  - hello-node
  - discord-notifier
  - finance-market-data-puller
  - expenses-api
  - telegram-bot
  - expenses-ui
  # - expenses-receiver
  # - server
  # - client
transformers:
  - auth-transformer.yaml
